apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-practice-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-practice-app
  template:
    metadata:
      labels:
        app: k8s-practice-app
    spec:
      containers:
      - name: k8s-practice-app
        image: k8s-practice-app:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-practice-app-service
spec:
  selector:
    app: k8s-practice-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
